### ISSUE TITLE
Keys should embed their own scale

### ISSUE THREAD

**Issue by ArnaudCalmettes** [ArnaudCalmettes/monk#3]
In the first draft, keys are clonable constants and they can produce a scale (a vector of Notes). That's cool, but when it comes to working intensely with them, for instance to check if a bunch of notes are diatonic to the key, it is going to be highly inefficient because the scale will be recomputed at each call.

I suggest that the current `Key` struct is renamed `KeyRoot`, `KeySpec` or even `KeyName`, and that the actual `Key` struct is constructed using such a root, so it can "embed" the scale and avoid recomputing it at each method call.

To make it simpler : keys should be created using `Key::new(G_FLAT_MAJOR)` instead of directly referring to `KEY_G_FLAT_MAJOR`.

# TODO

- [ ] Rename the current `Key` struct to a more suitable name (`KeyName` seems fine).
- [ ] Rename `KEY_FOO_BAR` constants to `FOO_BAR`.
- [ ] Define a `Key` struct as something that is built using the `KeyName` (we don't really want people to mess with "C triple-flat minor", do we ?) and that embeds its own `Scale`.
- [ ] Update the rust-doc comments and tests.
