### ISSUE TITLE
Bootstrap the CI

### ISSUE THREAD

**Issue by ArnaudCalmettes** [ArnaudCalmettes/monk#5]
Let's get serious and bootstrap the CI for this project, using CircleCI.

It's the actual first time I'm taking a project this seriously on Github, so it's going to require a bit of ramp-up on my side. :)

# TODO

- [x] Commits get tested (including the doc).
- [x] The build passes.
- [x] We show that neat "build: passing" badge in the project description.

**Comment by ArnaudCalmettes** [comment]
That wasn't too complicated, was it ? :)
